services:
  db:
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: typetale
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
volumes:
  mysql_data: